using System;

namespace Lawn
{
    public enum ZombieType
    {
        Invalid = -1,
        Normal,
        Flag,
        TrafficCone,
        Polevaulter,
        Pail,
        Newspaper,
        Door,
        Football,
        Dancer,
        BackupDancer,
        DuckyTube,
        Snorkel,
        Zamboni,
        Bobsled,
        DolphinRider,
        JackInTheBox,
        Balloon,
        Digger,
        Pogo,
        Yeti,
        Bungee,
        Ladder,
        Catapult,
        Gargantuar,
        Imp,
        Boss,
        PeaHead,
        WallnutHead,
        RepeaterHead,
        JalapenoHead,
        GatlingHead,
        SquashHead,
        TallnutHead,
        RedeyeGargantuar,
        Mustache,
        DoorCone,
        DoorPail,
        PogoPail,
        PogoHead,
        FirepeaHead,
        TallnutDoor,
        FlagCone,
        ZombieTypesCount,
        CachedPolevaulterWithPole,
        CachedZombieTypesCount
    }
}
